# Generated by Django 5.0 on 2025-09-17 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key_encrypted', models.TextField(blank=True, null=True)),
                ('backup_tokens_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Two Factor',
                'verbose_name_plural': 'User Two Factors',
                'db_table': 'auth_user_two_factor',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField()),
                ('attempt_type', models.CharField(choices=[('totp', 'TOTP Code'), ('backup', 'Backup Code')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Attempt',
                'verbose_name_plural': 'Two Factor Attempts',
                'db_table': 'auth_two_factor_attempt',
                'indexes': [models.Index(fields=['user', 'created_at'], name='auth_two_fa_user_id_45f71e_idx'), models.Index(fields=['ip_address', 'created_at'], name='auth_two_fa_ip_addr_dce5aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user_two_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='authentication.usertwofactor')),
            ],
            options={
                'verbose_name': 'Two Factor Backup Code',
                'verbose_name_plural': 'Two Factor Backup Codes',
                'db_table': 'auth_two_factor_backup_code',
                'indexes': [models.Index(fields=['code_hash'], name='auth_two_fa_code_ha_91518f_idx'), models.Index(fields=['is_used'], name='auth_two_fa_is_used_ad75a7_idx')],
            },
        ),
    ]
