version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: google-auth-backend-dev
    ports:
      - "8007:8007"
    environment:
      # Core Django Settings
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      
      # CORS/CSRF Settings (Development - more permissive)
      - CORS_ALLOWED_ORIGINS=http://localhost:3007,http://frontend:3007
      - CSRF_TRUSTED_ORIGINS=http://localhost:3007,http://frontend:3007
      - CORS_ALLOW_ALL_ORIGINS=True
      - CSRF_COOKIE_SECURE=False
      - SESSION_COOKIE_SECURE=False
      
      # JWT Settings
      - JWT_ACCESS_TOKEN_LIFETIME_MINUTES=15
      - JWT_REFRESH_TOKEN_LIFETIME_DAYS=7
      
      # Authentication & Security
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY:-}
      - RECAPTCHA_ENABLED=${RECAPTCHA_ENABLED:-true}
      - RECAPTCHA_MIN_SCORE=${RECAPTCHA_MIN_SCORE:-0.5}
      
      # Email Service
      - SENDINBLUE_API_KEY=${SENDINBLUE_API_KEY:-}
      
      # Payment Processing (Development/Sandbox)
      - GOOGLE_PAY_MERCHANT_ID=${GOOGLE_PAY_MERCHANT_ID:-}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID:-}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET:-}
      - PAYPAL_MODE=${PAYPAL_MODE:-sandbox}
    volumes:
      - ./apps/backend:/app
      - backend_static:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8007"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    container_name: google-auth-frontend-dev
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8007
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
      - NEXT_PUBLIC_GOOGLE_PAY_MERCHANT_ID=${GOOGLE_PAY_MERCHANT_ID:-}
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_static:

networks:
  app-network:
    driver: bridge

