version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: google-auth-backend
    ports:
      - "8003:8003"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3003,http://frontend:3003
      - CSRF_TRUSTED_ORIGINS=http://localhost:3003,http://frontend:3003
      - CORS_ALLOW_ALL_ORIGINS=False
      - CSRF_COOKIE_SECURE=False
      - SESSION_COOKIE_SECURE=False
      - JWT_ACCESS_TOKEN_LIFETIME_MINUTES=15
      - JWT_REFRESH_TOKEN_LIFETIME_DAYS=7
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - SENDINBLUE_API_KEY=${SENDINBLUE_API_KEY:-}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY:-}
      - RECAPTCHA_ENABLED=${RECAPTCHA_ENABLED:-true}
      - RECAPTCHA_MIN_SCORE=${RECAPTCHA_MIN_SCORE:-0.5}
    volumes:
      - ./apps/backend:/app
      - backend_static:/app/staticfiles
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8003"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: google-auth-frontend
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8003
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_static:

networks:
  app-network:
    driver: bridge

